version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

  commands:
    - pip install poetry
    - poetry config virtualenvs.create false
    - poetry install --only doc
    - mkdocs build -d $READTHEDOCS_OUTPUT/html/

mkdocs:
  configuration: mkdocs.yml
