site_name: Melodica Notes
repo_url: https://github.com/vhsenna/melodica-notes
repo_name: vhsenna/melodica-notes
edit_uri: tree/main/docs

theme:
  name: material

markdown_extensions:
  - attr_list

extra_css:
  - stylesheets/extra.css

watch:
  - melodica_notes

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [melodica_notes]
